# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SMeter_QA.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1200, 853)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 853))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_1)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_database_setting = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_database_setting.sizePolicy().hasHeightForWidth())
        self.pushButton_database_setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_database_setting.setFont(font)
        self.pushButton_database_setting.setObjectName("pushButton_database_setting")
        self.verticalLayout_2.addWidget(self.pushButton_database_setting)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.ComboBox_factory = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_factory.setFont(font)
        self.ComboBox_factory.setEditable(False)
        self.ComboBox_factory.setObjectName("ComboBox_factory")
        self.ComboBox_factory.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_factory)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton_batch = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_batch.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_batch.setFont(font)
        self.pushButton_batch.setObjectName("pushButton_batch")
        self.verticalLayout_2.addWidget(self.pushButton_batch)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.Label = QtWidgets.QLabel(self.groupBox_3)
        self.Label.setObjectName("Label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.ComboBox_batch = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_batch.setFont(font)
        self.ComboBox_batch.setEditable(True)
        self.ComboBox_batch.setObjectName("ComboBox_batch")
        self.ComboBox_batch.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_batch)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.Label_alert_start = QtWidgets.QLabel(self.groupBox_3)
        self.Label_alert_start.setObjectName("Label_alert_start")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_alert_start)
        self.Label_alert_end = QtWidgets.QLabel(self.groupBox_3)
        self.Label_alert_end.setObjectName("Label_alert_end")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_alert_end)
        self.DateTimeEdit_alert_end = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeEdit_alert_end.sizePolicy().hasHeightForWidth())
        self.DateTimeEdit_alert_end.setSizePolicy(sizePolicy)
        self.DateTimeEdit_alert_end.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_alert_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(23, 59, 59)))
        self.DateTimeEdit_alert_end.setCalendarPopup(True)
        self.DateTimeEdit_alert_end.setObjectName("DateTimeEdit_alert_end")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_alert_end)
        self.DateTimeEdit_alert_start = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeEdit_alert_start.sizePolicy().hasHeightForWidth())
        self.DateTimeEdit_alert_start.setSizePolicy(sizePolicy)
        self.DateTimeEdit_alert_start.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_alert_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_alert_start.setCalendarPopup(True)
        self.DateTimeEdit_alert_start.setObjectName("DateTimeEdit_alert_start")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_alert_start)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.pushButton_alert = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_alert.sizePolicy().hasHeightForWidth())
        self.pushButton_alert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_alert.setFont(font)
        self.pushButton_alert.setObjectName("pushButton_alert")
        self.verticalLayout_2.addWidget(self.pushButton_alert)
        self.label_factory = QtWidgets.QLabel(self.groupBox_3)
        self.label_factory.setObjectName("label_factory")
        self.verticalLayout_2.addWidget(self.label_factory)
        self.label_batch = QtWidgets.QLabel(self.groupBox_3)
        self.label_batch.setObjectName("label_batch")
        self.verticalLayout_2.addWidget(self.label_batch)
        self.label_StartDate_alert = QtWidgets.QLabel(self.groupBox_3)
        self.label_StartDate_alert.setObjectName("label_StartDate_alert")
        self.verticalLayout_2.addWidget(self.label_StartDate_alert)
        self.label_EndDate_alert = QtWidgets.QLabel(self.groupBox_3)
        self.label_EndDate_alert.setObjectName("label_EndDate_alert")
        self.verticalLayout_2.addWidget(self.label_EndDate_alert)
        self.label_stationID = QtWidgets.QLabel(self.groupBox_3)
        self.label_stationID.setObjectName("label_stationID")
        self.verticalLayout_2.addWidget(self.label_stationID)
        self.label_meterID = QtWidgets.QLabel(self.groupBox_3)
        self.label_meterID.setObjectName("label_meterID")
        self.verticalLayout_2.addWidget(self.label_meterID)
        self.label_num = QtWidgets.QLabel(self.groupBox_3)
        self.label_num.setObjectName("label_num")
        self.verticalLayout_2.addWidget(self.label_num)
        self.label_FPY = QtWidgets.QLabel(self.groupBox_3)
        self.label_FPY.setObjectName("label_FPY")
        self.verticalLayout_2.addWidget(self.label_FPY)
        self.label_mean = QtWidgets.QLabel(self.groupBox_3)
        self.label_mean.setObjectName("label_mean")
        self.verticalLayout_2.addWidget(self.label_mean)
        self.label_var = QtWidgets.QLabel(self.groupBox_3)
        self.label_var.setObjectName("label_var")
        self.verticalLayout_2.addWidget(self.label_var)
        self.label_skew = QtWidgets.QLabel(self.groupBox_3)
        self.label_skew.setObjectName("label_skew")
        self.verticalLayout_2.addWidget(self.label_skew)
        self.label_kurtosis = QtWidgets.QLabel(self.groupBox_3)
        self.label_kurtosis.setObjectName("label_kurtosis")
        self.verticalLayout_2.addWidget(self.label_kurtosis)
        spacerItem = QtWidgets.QSpacerItem(118, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_alert = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_alert.setAlternatingRowColors(True)
        self.tableWidget_alert.setObjectName("tableWidget_alert")
        self.tableWidget_alert.setColumnCount(0)
        self.tableWidget_alert.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_alert, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.ComboBox_factory_sub = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_factory_sub.setFont(font)
        self.ComboBox_factory_sub.setEditable(False)
        self.ComboBox_factory_sub.setObjectName("ComboBox_factory_sub")
        self.ComboBox_factory_sub.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ComboBox_factory_sub)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.pushButton_batch_sub = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_batch_sub.setObjectName("pushButton_batch_sub")
        self.verticalLayout.addWidget(self.pushButton_batch_sub)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.ComboBox_batch_sub = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_batch_sub.setFont(font)
        self.ComboBox_batch_sub.setEditable(True)
        self.ComboBox_batch_sub.setObjectName("ComboBox_batch_sub")
        self.ComboBox_batch_sub.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ComboBox_batch_sub)
        self.Label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.ComboBox_itemname = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_itemname.setFont(font)
        self.ComboBox_itemname.setObjectName("ComboBox_itemname")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.ComboBox_itemname.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ComboBox_itemname)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.Label_alert_start_2 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_alert_start_2.setObjectName("Label_alert_start_2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_alert_start_2)
        self.DateTimeEdit_subalert_start = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.DateTimeEdit_subalert_start.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_subalert_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_subalert_start.setCalendarPopup(True)
        self.DateTimeEdit_subalert_start.setObjectName("DateTimeEdit_subalert_start")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_subalert_start)
        self.Label_alert_end_2 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_alert_end_2.setObjectName("Label_alert_end_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_alert_end_2)
        self.DateTimeEdit_subalert_end = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.DateTimeEdit_subalert_end.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_subalert_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(23, 59, 59)))
        self.DateTimeEdit_subalert_end.setCalendarPopup(True)
        self.DateTimeEdit_subalert_end.setObjectName("DateTimeEdit_subalert_end")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_subalert_end)
        self.verticalLayout.addLayout(self.formLayout_6)
        self.pushButton_subalert = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_subalert.setFont(font)
        self.pushButton_subalert.setObjectName("pushButton_subalert")
        self.verticalLayout.addWidget(self.pushButton_subalert)
        self.label_factory_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_factory_sub.setObjectName("label_factory_sub")
        self.verticalLayout.addWidget(self.label_factory_sub)
        self.label_batch_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_batch_sub.setObjectName("label_batch_sub")
        self.verticalLayout.addWidget(self.label_batch_sub)
        self.label_itemname = QtWidgets.QLabel(self.groupBox_5)
        self.label_itemname.setObjectName("label_itemname")
        self.verticalLayout.addWidget(self.label_itemname)
        self.label_StartDate_subalert = QtWidgets.QLabel(self.groupBox_5)
        self.label_StartDate_subalert.setObjectName("label_StartDate_subalert")
        self.verticalLayout.addWidget(self.label_StartDate_subalert)
        self.label_EndDate_subalert = QtWidgets.QLabel(self.groupBox_5)
        self.label_EndDate_subalert.setObjectName("label_EndDate_subalert")
        self.verticalLayout.addWidget(self.label_EndDate_subalert)
        self.label_stationID_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_stationID_sub.setObjectName("label_stationID_sub")
        self.verticalLayout.addWidget(self.label_stationID_sub)
        self.label_meterID_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_meterID_sub.setObjectName("label_meterID_sub")
        self.verticalLayout.addWidget(self.label_meterID_sub)
        self.label_num_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_num_sub.setObjectName("label_num_sub")
        self.verticalLayout.addWidget(self.label_num_sub)
        self.label_FPY_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_FPY_sub.setObjectName("label_FPY_sub")
        self.verticalLayout.addWidget(self.label_FPY_sub)
        self.label_mean_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_mean_sub.setObjectName("label_mean_sub")
        self.verticalLayout.addWidget(self.label_mean_sub)
        self.label_var_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_var_sub.setObjectName("label_var_sub")
        self.verticalLayout.addWidget(self.label_var_sub)
        self.label_skew_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_skew_sub.setObjectName("label_skew_sub")
        self.verticalLayout.addWidget(self.label_skew_sub)
        self.label_kurtosis_sub = QtWidgets.QLabel(self.groupBox_5)
        self.label_kurtosis_sub.setObjectName("label_kurtosis_sub")
        self.verticalLayout.addWidget(self.label_kurtosis_sub)
        spacerItem1 = QtWidgets.QSpacerItem(118, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_subalert = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget_subalert.setAlternatingRowColors(True)
        self.tableWidget_subalert.setObjectName("tableWidget_subalert")
        self.tableWidget_subalert.setColumnCount(0)
        self.tableWidget_subalert.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget_subalert, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.Label_alert_start_3 = QtWidgets.QLabel(self.groupBox_7)
        self.Label_alert_start_3.setObjectName("Label_alert_start_3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_alert_start_3)
        self.Label_alert_end_3 = QtWidgets.QLabel(self.groupBox_7)
        self.Label_alert_end_3.setObjectName("Label_alert_end_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_alert_end_3)
        self.DateTimeEdit_terror_end = QtWidgets.QDateTimeEdit(self.groupBox_7)
        self.DateTimeEdit_terror_end.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_terror_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(23, 59, 59)))
        self.DateTimeEdit_terror_end.setCalendarPopup(True)
        self.DateTimeEdit_terror_end.setObjectName("DateTimeEdit_terror_end")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_terror_end)
        self.DateTimeEdit_terror_start = QtWidgets.QDateTimeEdit(self.groupBox_7)
        self.DateTimeEdit_terror_start.setMinimumSize(QtCore.QSize(0, 31))
        self.DateTimeEdit_terror_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_terror_start.setCalendarPopup(True)
        self.DateTimeEdit_terror_start.setObjectName("DateTimeEdit_terror_start")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_terror_start)
        self.verticalLayout_8.addLayout(self.formLayout_7)
        self.pushButton_terror = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_terror.setFont(font)
        self.pushButton_terror.setObjectName("pushButton_terror")
        self.verticalLayout_8.addWidget(self.pushButton_terror)
        self.label_StartDate_terror = QtWidgets.QLabel(self.groupBox_7)
        self.label_StartDate_terror.setObjectName("label_StartDate_terror")
        self.verticalLayout_8.addWidget(self.label_StartDate_terror)
        self.label_EndDate_terror = QtWidgets.QLabel(self.groupBox_7)
        self.label_EndDate_terror.setObjectName("label_EndDate_terror")
        self.verticalLayout_8.addWidget(self.label_EndDate_terror)
        self.label_stationID_terror = QtWidgets.QLabel(self.groupBox_7)
        self.label_stationID_terror.setObjectName("label_stationID_terror")
        self.verticalLayout_8.addWidget(self.label_stationID_terror)
        self.label_num_terror = QtWidgets.QLabel(self.groupBox_7)
        self.label_num_terror.setObjectName("label_num_terror")
        self.verticalLayout_8.addWidget(self.label_num_terror)
        self.label_mean_terror = QtWidgets.QLabel(self.groupBox_7)
        self.label_mean_terror.setObjectName("label_mean_terror")
        self.verticalLayout_8.addWidget(self.label_mean_terror)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(118, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setCheckable(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget_terror = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget_terror.setAlternatingRowColors(True)
        self.tableWidget_terror.setObjectName("tableWidget_terror")
        self.tableWidget_terror.setColumnCount(0)
        self.tableWidget_terror.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidget_terror, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_6.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电能表室内检定质量分析工具"))
        self.groupBox_3.setTitle(_translate("MainWindow", "设置"))
        self.pushButton_database_setting.setText(_translate("MainWindow", "数据库配置"))
        self.Label_3.setText(_translate("MainWindow", "厂家"))
        self.ComboBox_factory.setItemText(0, _translate("MainWindow", "全部厂家"))
        self.pushButton_batch.setText(_translate("MainWindow", "获取批次"))
        self.Label.setText(_translate("MainWindow", "批次"))
        self.ComboBox_batch.setItemText(0, _translate("MainWindow", "全部批次"))
        self.Label_alert_start.setText(_translate("MainWindow", "起"))
        self.Label_alert_end.setText(_translate("MainWindow", "止"))
        self.DateTimeEdit_alert_end.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.DateTimeEdit_alert_start.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton_alert.setText(_translate("MainWindow", "显示数据"))
        self.label_factory.setText(_translate("MainWindow", "厂家："))
        self.label_batch.setText(_translate("MainWindow", "批次："))
        self.label_StartDate_alert.setText(_translate("MainWindow", "起始时间："))
        self.label_EndDate_alert.setText(_translate("MainWindow", "结束时间："))
        self.label_stationID.setText(_translate("MainWindow", "检定单元："))
        self.label_meterID.setText(_translate("MainWindow", "检定表位："))
        self.label_num.setText(_translate("MainWindow", "数据量："))
        self.label_FPY.setText(_translate("MainWindow", "合格率："))
        self.label_mean.setText(_translate("MainWindow", "期望："))
        self.label_var.setText(_translate("MainWindow", "方差："))
        self.label_skew.setText(_translate("MainWindow", "偏度："))
        self.label_kurtosis.setText(_translate("MainWindow", "峰度："))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据表显示"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "总预警"))
        self.groupBox_5.setTitle(_translate("MainWindow", "设置"))
        self.Label_2.setText(_translate("MainWindow", "厂家"))
        self.ComboBox_factory_sub.setItemText(0, _translate("MainWindow", "全部厂家"))
        self.pushButton_batch_sub.setText(_translate("MainWindow", "获取批次"))
        self.Label_4.setText(_translate("MainWindow", "批次"))
        self.ComboBox_batch_sub.setItemText(0, _translate("MainWindow", "全部批次"))
        self.Label_5.setText(_translate("MainWindow", "项目"))
        self.ComboBox_itemname.setItemText(0, _translate("MainWindow", "P+,H,(1.0Ib,1.0)"))
        self.ComboBox_itemname.setItemText(1, _translate("MainWindow", "P+,H,(1.0Ib,0.5L)"))
        self.ComboBox_itemname.setItemText(2, _translate("MainWindow", "P+,H,(0.2Ib,0.5L)"))
        self.ComboBox_itemname.setItemText(3, _translate("MainWindow", "P+,H,(0.1Ib,1.0)"))
        self.ComboBox_itemname.setItemText(4, _translate("MainWindow", "P+,H,(0.1Ib,0.5L)"))
        self.ComboBox_itemname.setItemText(5, _translate("MainWindow", "P+,H,(0.05Ib,1.0)"))
        self.ComboBox_itemname.setItemText(6, _translate("MainWindow", "P+,H,(Imax,1.0)"))
        self.ComboBox_itemname.setItemText(7, _translate("MainWindow", "P+,H,(Imax,0.5L)"))
        self.ComboBox_itemname.setItemText(8, _translate("MainWindow", "P+,H,(0.5Imax,1.0)"))
        self.ComboBox_itemname.setItemText(9, _translate("MainWindow", "P+,H,(0.5Imax,0.5L)"))
        self.Label_alert_start_2.setText(_translate("MainWindow", "起"))
        self.DateTimeEdit_subalert_start.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.Label_alert_end_2.setText(_translate("MainWindow", "止"))
        self.DateTimeEdit_subalert_end.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton_subalert.setText(_translate("MainWindow", "显示数据"))
        self.label_factory_sub.setText(_translate("MainWindow", "厂家："))
        self.label_batch_sub.setText(_translate("MainWindow", "批次："))
        self.label_itemname.setText(_translate("MainWindow", "项目："))
        self.label_StartDate_subalert.setText(_translate("MainWindow", "起始时间："))
        self.label_EndDate_subalert.setText(_translate("MainWindow", "结束时间："))
        self.label_stationID_sub.setText(_translate("MainWindow", "检定单元："))
        self.label_meterID_sub.setText(_translate("MainWindow", "检定表位："))
        self.label_num_sub.setText(_translate("MainWindow", "数据量："))
        self.label_FPY_sub.setText(_translate("MainWindow", "合格率："))
        self.label_mean_sub.setText(_translate("MainWindow", "期望："))
        self.label_var_sub.setText(_translate("MainWindow", "方差："))
        self.label_skew_sub.setText(_translate("MainWindow", "偏度："))
        self.label_kurtosis_sub.setText(_translate("MainWindow", "峰度："))
        self.groupBox_6.setTitle(_translate("MainWindow", "数据表显示"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "分项预警"))
        self.groupBox_7.setTitle(_translate("MainWindow", "设置"))
        self.Label_alert_start_3.setText(_translate("MainWindow", "起"))
        self.Label_alert_end_3.setText(_translate("MainWindow", "止"))
        self.DateTimeEdit_terror_end.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.DateTimeEdit_terror_start.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton_terror.setText(_translate("MainWindow", "显示数据"))
        self.label_StartDate_terror.setText(_translate("MainWindow", "起始时间："))
        self.label_EndDate_terror.setText(_translate("MainWindow", "结束时间："))
        self.label_stationID_terror.setText(_translate("MainWindow", "检定单元："))
        self.label_num_terror.setText(_translate("MainWindow", "数据量："))
        self.label_mean_terror.setText(_translate("MainWindow", "期望："))
        self.groupBox_8.setTitle(_translate("MainWindow", "数据表显示"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "日计时误差预警"))
        self.label.setText(_translate("MainWindow", "电能表室内检定质量分析工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "检定质量分析"))

